### ISSUE TITLE
Vim 翻译统一

### ISSUE THREAD

**Issue by ksyx** [CN-missemi/CN_missemi#17]
我当前在按下列 mapping：
- navigate - 移动光标
- buffer - (不翻)
- command - 命令 （e.g. movement command）
- Normal 模式；Visual Block 模式（单词首字母大写）
- Home Row：键盘最中间一行（ref: Caps Lock, hjkl）
- Idea：（核心）思想
  - @CoelacanthusHex 的“设计哲学”翻得好鸭

**Comment by GNAQ** [comment]
Press ** key / do ** command / write ** command：

一个按键 / 一套组合键 & 非输入性内容（实时触发）：翻为**「按下」**

一系列（非瞬时地）按键 / 先后按下很多按键 / 输入性内容（非实时触发）：翻为**「键入」**

**Comment by GNAQ** [comment]
window & tab 的翻译问题：window 和 tab 该被翻译吗？ #19 #4

**Comment by GNAQ** [comment]
若内容关于 Vim，则 window 和 tab 保留原样

若关于其他编辑器，则翻译为窗口和标签页。

**Comment by GNAQ** [comment]
Command Line Mode 翻为「命令行模式」

其余模式不翻译，即：Normal 模式 / Visual 模式

**Comment by GNAQ** [comment]
(a / some / ...) **chunk** of text  -> 译为「一**段**文本」

**Comment by GNAQ** [comment]
Vim **modifier** -> 修饰符
