### ISSUE TITLE
第四讲还有希望压制出来吗？

### ISSUE THREAD

**Issue by opptimus** [CN-missemi/CN_missemi#46]
再次感谢字幕组的无私奉献

**Comment by ksyx** [comment]
大家最近比较忙 可能要到暑假之后 感谢你的支持。

**Comment by GNAQ** [comment]
@opptimus 这个事情的问题在我，责任也在我。我真的没有想到开学之后会这么忙，而且大学一年级还存在二次选拔，竞争比较激烈，而我成绩不佳，可能还是会把很多时间放在学习（内卷）上。
