### ISSUE TITLE
请问我可以参加到这个项目吗？

### ISSUE THREAD

**Issue by symkube** [CN-missemi/CN_missemi#47]
在b站看到了这个课程，非常喜欢，但是看到贵组似乎暂停了更新，不知道是不是有一些工作量上的压力，请问我可以参加到这个项目里，做一些工作吗？

**Comment by Officeyutong** [comment]
之前因为主要的staff课业太忙暂时停更了，现在到暑假会继续的

**Comment by GNAQ** [comment]
可否请您发送任意联系内容到我的电子邮箱： no1061234176@outlook.com，谢谢。

Could you please send whatever message to this email address to let me get in touch? Thank you.
